### PR TITLE
Different background for sent/received messages in chat.

### PR DESCRIPTION
**Pull request by olaore**
# Description

Added different background for sent/received messages in chat.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

Remove any items which are not applicable.

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

## Linkt to Trello card
https://trello.com/c/604MCywj/93-add-different-background-for-sent-and-received-messages

### CODE REVIEW

**Comment by olaore** [comment]
[Add different background for sent and received messages in chat](https://trello.com/c/604MCywj/93-add-different-background-for-sent-and-received-messages-in-chat)

**Review by evansibok — CHANGES_REQUESTED** [review]
1. I think the color for the left chat can be something better other than the grey. I'll recommend you take out the grey.
2. Please pull from develop branch and resolve any possible conflicts. Then I'll review again.

**Comment by olaore** [comment]
> 1. I think the color for the left chat can be something better other than the grey. I'll recommend you take out the grey.
> 2. Please pull from develop branch and resolve any possible conflicts. Then I'll review again.

Done.

**Review by evansibok — APPROVED** [review]
Looks great!

**Pull request merged**
