### PR TITLE
Add required section notices

### PR DESCRIPTION
**Pull request by evansibok**
# Description
- Add a new state boolean to set if a review form is applicable or not
- If review form is `checked` do not call the action.
- Make sure submit button submits only allowed reviews
- Set UI required text to sections
- Disable form fields for disabled sections
- Disable button when required fields are empty.

Describe change or new feature here.

## Type of change
Chore

- [x] New feature (non-breaking change which adds functionality)

## Checklist

Remove any items which are not applicable.

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

## Linkt to Trello card
<blockquote class="trello-card"><a href="https://trello.com/c/hjQrh2ef/87-notify-user-of-optional-fields-in-add-review-form">Notify user of optional fields in add review form</a></blockquote>

### CODE REVIEW

**Review by rodrigograca31 — CHANGES_REQUESTED** [review]
1. It allows me to submit empty fields and then crashes because of that. Allows no company and that crashes the API. 
2. Then allows for other text fields to be empty and that breaks the UI after submitting. Doesn't even actually submit.

The `Submit` button should be disabled like before until all the fields are filled.

Not approving :cry: :sob:

**Comment by evansibok** [comment]
> 1. It allows me to submit empty fields and then crashes because of that. Allows no company and that crashes the API.
> 2. Then allows for other text fields to be empty and that breaks the UI after submitting. Doesn't even actually submit.
> 
> The `Submit` button should be disabled like before until all the fields are filled.
> 
> Not approving 😢 😭
> 

**1**. Please list the empty fields you're able to submit, so I can take a look at it. The crash comes from the chat component issue, it's not related to the form.

**2**. What other text fields are you referring to that are allowed to be empty. The form has been updated so you can't submit all three types of reviews at once. The only required review is the General review, the salary review and interview review are only required if that's the review you want to fill. That's why there's a checkbox that allows you to disable or enable any of those sections. So if you don't want to submit a salary review but an interview review you will be able to disable the salary review and submit the interview review alongside the general review.

**Comment by rodrigograca31** [comment]
1. and 2. Any field. Any field can now be empty. The submit button is always enabled.
that means the user can miss fields and click `Submit` and then it crashes. 

image

**Comment by evansibok** [comment]
[Notify user of optional fields in add review form](https://trello.com/c/hjQrh2ef/87-notify-user-of-optional-fields-in-add-review-form)

**Review by rodrigograca31 — APPROVED** [review]
Seems good. just remove `JSON.stringify` debug and we can merge after that

P.S. I just solved the conflict so please pull the branch before :)

**Pull request merged**
