### PR TITLE
Test chat ui

### PR DESCRIPTION
**Pull request by olaore**
# Description
- Add test for ChatButton.jsx
- Add Test for Chat.jsx

Test for chat components.

## Type of change
- [x] Test

## Checklist
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

## Linkt to Trello card
<blockquote class="trello-card"><a href="https://trello.com/c/CDBZezj7/83-test-chat-message-interface">Test Chat Message Interface</a></blockquote>

### CODE REVIEW

**Comment by olaore** [comment]
Same PR as yesterday. Another PR because the Netlify build test for the previous is stuck for >24 hours

**Comment by ola-dola** [comment]
[Test frontend layout code for chat interface](https://trello.com/c/l4bV4JXK/82-test-frontend-layout-code-for-chat-interface)

**Review by rodrigograca31 — APPROVED** [review]

**Review by rodrigograca31 — APPROVED** [review]
Took me a while to review because of that merge, had to make sure everything was merged with no regressions. I'm not 100% confident but I'm 99% so I will approve!

**Comment by olaore** [comment]
> Took me a while to review because of that merge, had to make sure everything was merged with no regressions. I'm not 100% confident but I'm 99% so I will approve!
> 
> 

99% is my lucky number so I'll take it!

**Pull request merged**
