### PR TITLE
Create new 'add a review' navbar

### PR DESCRIPTION
**Pull request by evansibok**
# Description
Add a new navbar with the 'add a review' button.

## Type of change
Styling

## Checklist
- [ ] Move the searchbar to the new navbar
- [ ] Remove styling bugs from previous code

Remove any items which are not applicable.

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works.

## Linkt to Trello card
<blockquote class="trello-card"><a href="https://trello.com/c/QadqMGZE/25-dashboard-redesign">Dashboard Redesign</a></blockquote>

### CODE REVIEW

**Comment by ola-dola** [comment]
Tried locally. No conflicts. Code looks good.

**Comment by evansibok** [comment]
> Any reason why the sign out button is on the left instead of the right?
> Also, The navbar looks a little too huge.

- [ ] That's because that's a separate navbar on its own. When you look at the wireframe, you'll find there's supposed to be a navbar at the top with the logo and menu icon. The top navbar is being styled using flexbox and it's shifting to the left because there's no other content there to adjust the positioning. 
- [ ] When the other top bar has been done we can look at proper spacing and position. That's my thought on it. This PR is a representation on the added of the new navbar and doesn't include the other tasks.

**Comment by evansibok** [comment]
[Dashboard Redesign](https://trello.com/c/QadqMGZE/25-dashboard-redesign)

**Comment by evansibok** [comment]
> Code looks good overall but like @kip-guile said the `sign out` button is out of place:
> 
> image
> 
> NOT ACCEPTABLE! 😂

😂
This pull requests reflects my work on adding the navbar where we have the searchbar and the 'add a review' button. Jordan and Ola are working on the topnav where we have the signout and the sidenav. While working on their respective files, they'll get to fix that.

**Comment by rodrigograca31** [comment]
@evansibok now for real I dont think its professional to accept a PR that breaks something else... Also the button does nothing so its a WIP so why should we accept the PR? :thinking:

**Comment by rodrigograca31** [comment]
@evansibok Should I just accept it? so that we dont waste more time?

**Pull request closed without merging**
